"""Added DTConfig table

Revision ID: 2e68459ecdc0
Revises: 8a204bbb5de3
Create Date: 2019-11-13 11:40:20.460225

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "2e68459ecdc0"
down_revision = "8a204bbb5de3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dicom_transit_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("LORISurl", sa.String(), nullable=True),
        sa.Column(
            "LORISusername",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column(
            "LORISpassword",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column("timepoint_prefix", sa.String(), nullable=True),
        sa.Column("institutionID", sa.String(), nullable=True),
        sa.Column("institutionName", sa.String(), nullable=True),
        sa.Column("projectID_dic", sa.String(), nullable=True),
        sa.Column("LocalDatabasePath", sa.String(), nullable=True),
        sa.Column("LogPath", sa.String(), nullable=True),
        sa.Column("ZipPath", sa.String(), nullable=True),
        sa.Column("DevOrthancIP", sa.String(), nullable=True),
        sa.Column(
            "DevOrthancUser",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column(
            "DevOrthancPassword",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column("ProdOrthancIP", sa.String(), nullable=True),
        sa.Column(
            "ProdOrthancUser",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column(
            "ProdOrthancPassword",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dicom_transit_config_timestamp"),
        "dicom_transit_config",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dicom_transit_config_timestamp"), table_name="dicom_transit_config"
    )
    op.drop_table("dicom_transit_config")
    # ### end Alembic commands ###
