"""Included RedCap related settings

Revision ID: 2ff7100d055b
Revises: 2e68459ecdc0
Create Date: 2019-11-26 14:27:05.763152

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "2ff7100d055b"
down_revision = "2e68459ecdc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dicom_transit_config",
        sa.Column("CNFUN_CONNECTION_STRING", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("CNN_CONNECTION_STRING", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("COUCHDB_EXPORT_DATABASE", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("COUCHDB_EXPORT_ENABLED", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("COUCHDB_EXPORT_HOST", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("COUCHDB_EXPORT_PASSWORD", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("COUCHDB_EXPORT_PORT", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("COUCHDB_EXPORT_USER", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("MYSQL_EXPORT_DATABASE", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("MYSQL_EXPORT_ENABLED", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("MYSQL_EXPORT_HOST", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("MYSQL_EXPORT_PASSWORD", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("MYSQL_EXPORT_PORT", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("MYSQL_EXPORT_USER", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("NUMBER_OF_RECORDS_PER_BATCH", sa.Integer(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config", sa.Column("REDCAP_API_URL", sa.String(), nullable=True)
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("REDCAP_EXPORT_ENABLED", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("REDCAP_TOKEN_CNFUN_PATIENT", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("REDCAP_TOKEN_CNN_ADMISSION", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("REDCAP_TOKEN_CNN_BABY", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("REDCAP_TOKEN_CNN_MASTER", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column("REDCAP_TOKEN_CNN_MOTHER", sa.String(), nullable=True),
    )
    op.add_column(
        "dicom_transit_config",
        sa.Column(
            "USE_LOCAL_HOSPITAL_RECORD_NUMBERS_LIST", sa.Integer(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dicom_transit_config", "USE_LOCAL_HOSPITAL_RECORD_NUMBERS_LIST")
    op.drop_column("dicom_transit_config", "REDCAP_TOKEN_CNN_MOTHER")
    op.drop_column("dicom_transit_config", "REDCAP_TOKEN_CNN_MASTER")
    op.drop_column("dicom_transit_config", "REDCAP_TOKEN_CNN_BABY")
    op.drop_column("dicom_transit_config", "REDCAP_TOKEN_CNN_ADMISSION")
    op.drop_column("dicom_transit_config", "REDCAP_TOKEN_CNFUN_PATIENT")
    op.drop_column("dicom_transit_config", "REDCAP_EXPORT_ENABLED")
    op.drop_column("dicom_transit_config", "REDCAP_API_URL")
    op.drop_column("dicom_transit_config", "NUMBER_OF_RECORDS_PER_BATCH")
    op.drop_column("dicom_transit_config", "MYSQL_EXPORT_USER")
    op.drop_column("dicom_transit_config", "MYSQL_EXPORT_PORT")
    op.drop_column("dicom_transit_config", "MYSQL_EXPORT_PASSWORD")
    op.drop_column("dicom_transit_config", "MYSQL_EXPORT_HOST")
    op.drop_column("dicom_transit_config", "MYSQL_EXPORT_ENABLED")
    op.drop_column("dicom_transit_config", "MYSQL_EXPORT_DATABASE")
    op.drop_column("dicom_transit_config", "COUCHDB_EXPORT_USER")
    op.drop_column("dicom_transit_config", "COUCHDB_EXPORT_PORT")
    op.drop_column("dicom_transit_config", "COUCHDB_EXPORT_PASSWORD")
    op.drop_column("dicom_transit_config", "COUCHDB_EXPORT_HOST")
    op.drop_column("dicom_transit_config", "COUCHDB_EXPORT_ENABLED")
    op.drop_column("dicom_transit_config", "COUCHDB_EXPORT_DATABASE")
    op.drop_column("dicom_transit_config", "CNN_CONNECTION_STRING")
    op.drop_column("dicom_transit_config", "CNFUN_CONNECTION_STRING")
    # ### end Alembic commands ###
