"""post table

Revision ID: 8669596286b2
Revises: d4b6f489d4f7
Create Date: 2019-09-16 15:19:30.765369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8669596286b2"
down_revision = "d4b6f489d4f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password_hash", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_hash")
    # ### end Alembic commands ###
