"""Added additional diagnoses information collection process.

Revision ID: 8a204bbb5de3
Revises: ab45b4cf28ad
Create Date: 2019-11-01 17:33:10.115485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a204bbb5de3"
down_revision = "ab45b4cf28ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entry", sa.Column("dicharge_diagoses", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entry", "dicharge_diagoses")
    # ### end Alembic commands ###
