"""Added data entry related models

Revision ID: ab45b4cf28ad
Revises: 7cf416ee29c5
Create Date: 2019-10-01 18:01:32.779218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab45b4cf28ad"
down_revision = "7cf416ee29c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entry", sa.Column("mri_age", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entry", "mri_age")
    # ### end Alembic commands ###
